<p>In this sidebar, you'll find links to products I've found useful or inspiring. Full disclosure: sales from the Amazon ads support hosting and development costs.</p>
<p>The following books (or their earlier editions) are the ones that got me into psychology.</p>
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ss&ref=ss_til&ad_type=product_link&tracking_id=collabor8r-20&marketplace=amazon&region=US&placement=B000FC1KR0&asins=B000FC1KR0&linkId=55IDSLJNUXCLUZOM&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=4C659E&bg_color=FFFFFF">
</iframe>
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ss&ref=ss_til&ad_type=product_link&tracking_id=collabor8r-20&marketplace=amazon&region=US&placement=0321883322&asins=0321883322&linkId=Z2IZ7ZRDMS3PLJKV&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=4C659E&bg_color=FFFFFF">
</iframe>
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ss&ref=ss_til&ad_type=product_link&tracking_id=collabor8r-20&marketplace=amazon&region=US&placement=0840032986&asins=0840032986&linkId=6VXYR2QJXRTHJNTG&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=4C659E&bg_color=FFFFFF">
</iframe>
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ss&ref=ss_til&ad_type=product_link&tracking_id=collabor8r-20&marketplace=amazon&region=US&placement=0071390111&asins=0071390111&linkId=3W2UAVPFBUKOAG22&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=4C659E&bg_color=FFFFFF">
</iframe>