<p><h1>Teaching Philosophy</h1></p>
	<p>
	As a scientist educator who is well versed in the false nature vs. nurture dichotomy, I take a surprisingly nativist approach when teaching. My primary goal is not to fill my students with facts, but to help them unlock their inner scientists. The respect I have for students as potential peers waiting to be released has had a huge impact on both my approach to teaching and my commitment to push myself to become a better educator/mentor. To help my students unleash their inner scientists, I focus on the big questions, do my best to engage my students, utilize evidence-based practices, and continuously evaluate my performance for ways to improve my teaching effectiveness.
	</p>
<p><h1>The Big Questions</h1></p>
	<p>
	As a student, it seemed like most of my classes focused on the whats, wheres, and whens. Although the answers to these questions are important, they rarely seem as interesting or as challenging as the hows and whys. Unfortunately, many of the classes that focused on the whys and hows presented them as a matter of fact, thereby eliminating the element of question. Given the importance of these questions in driving science, this approach seems folly when educating aspiring scientists. It is also questionable from a cognitive perspective: by removing the questions from the conversation, the struggle to uncover answers is minimized and deep processing is traded for shallow. I do my best to keep the important questions at the forefront of my classes.
	</p>
	<p>
	To keep the questions at the forefront, I regularly question my students before we start to examine the established theories and evidence. A common question is why anyone should care about the topic. Questions probing their ideas about psychological phenomena and potential ways they could test their hypotheses also make regular appearances in my classes. Once so primed, my students seem better prepared to engage in and understand the day's materials. Often, they are also pleasantly surprised to find that their intuitions brought them to the right answer or, at least, on path to the right answer. The questions don't stop there, however. After introducing a theory or evidence, I again query my class about what predictions the theory would make, whether or not the evidence supports the theory, or even better, which theory does the evidence best support? The collaborative learning fostered by these questions helps my students think critically, draw connections between seemingly disparate areas, and meaningfully engage in the materials.
	</p>
<p><h1>Further Engaging My Students</h1></p>
	<p>
	I am passionate about psychology and, more broadly, science. My passion infuses my teaching with a sincerity and energy that positively engages my students (evaluations provided to select individuals upon request). To further engage my students I use unconventional demonstrations, discuss controversial topics, and approach mundane topics from unorthodox perspectives. For example, when covering psychopharmacology and addiction in my intro classes, I don't approach psychoactive drugs as dangerous substances. Instead I approach them as wondrous substances with sought after properties (e.g. euphoria). The surprise of hearing what appears to be an endorsement of engaging in drug abuse captures their attention just in time for the "real" lessons about the amazing adaptive abilities of our brains and the negative consequences of these adaptive mechanisms doing their jobs.
	</p>
<p><h1>Evidence-Based Instruction</h1></p>
	<p>
	Beyond engaging my students, I structure my classes to take strong advantage of the positive learning effects attributed to repetition, distributed studying, depth of processing, and immediate feedback. Before each class, I give my students study guides to help them focus on the important information and provide a framework around which they might organize their thoughts. To encourage students to use the study guides, I start most classes with a quiz based off the study guides before we discuss the day's topics. Thus, the students who prepare their guides, come to class, and review their notes have at least three exposures to the material before they ever take an exam. Immediately after each exam and quiz, I give my students access to the answer keys. Thus, my quizzes and exams serve as additional opportunities for my students to crystalize or correct their knowledge.
	</p>
<p><h1>Evaluation and Revision</h1></p>
	<p>
	Although I've been teaching a while, I'm still making significant changes to my courses in a continuing effort to improve my teaching efficacy. In this time, I've used lectures, discussions, and inter-teaching; and have found something of value in each method. Currently, I prepare as if I'm lecturing, use study-guides from inter-teaching, and do my utmost to foster discussion. Should my efforts at engaging my classes in discussion fail, my backup lectures are ready to go. Although the traditional end-of-semester evaluations and my own subjective impressions have been invaluable in this ongoing process of improvement, these sources of feedback often come too late to positively impact the students providing the feedback. In order to combat this problem, my students can submit anonymous feedback throughout the semester at <a href="http://wknapp.com/mailform">http://wknapp.com/mailform</a>.
	</p>
<p><h1>Final Thoughts</h1></p>
	<p>
	As a brief statement of philosophy, it's impossible to communicate all my thoughts about teaching. Many ideas are implied but not made explicit (e.g. building relationships based on mutual respect; or the importance of having fun in the classroom). Others are completely ignored (e.g. the importance of developing writing skills). Instead I wanted to share those attributes that are more unique to my philosophy. If you are interested in seeing how my philosophy has changed over time or in digging deeper into what I consider foundational beliefs, you are encouraged to visit 
	<a href="http://wknapp.com/teachingold">http://wknapp.com/teachingold</a>. Additionally, to find current course materials, visit <a href="http://wknapp.com/classes">http://wknapp.com/classes</a>.
	</p>